### ISSUE TITLE
Addresses cannot be entered manually 

### ISSUE THREAD

**Issue by ta3pks** [Khudsa/sincrodirs#2]
Addresses cannot be edited or added manually so it always create an extra unwanted folder with the same name as source folder if we could just add / in the end of the folder i guess this could be solved

**Comment by Anorelsan** [comment]
You can only select folders from the file system as a destination. Adding manual addresses it not supported right now. You can edit the destination folder if you select it, click on the "Add/Change folder" button and select another destination folder.
